// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eavxkaofxunvpxanyywx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhdnhrYW9meHVudnB4YW55eXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjI4NzEsImV4cCI6MjA2NjUzODg3MX0.07BRNl91jHJJsY8FX58ZSQBNCVM2NaPZqrcgRoYqJxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);